pipeline {
   agent any

   environment {
        HOME = '.'
        registry = "nemchinovrp/angular_kubernates"
        registryCredential = 'dockerhub'
   }

  stages {
    stage('Checkout Source') {
      steps {
        git url:'https://github.com/Nemchinovrp/Angular-Kubernates.git', branch:'master'
      }
    }

       stage('ls la') {
               steps {
                      echo "Hello World!"
                        sh "ls -la"
              }
        }

   stage('Build') {
            agent {
                 docker { image 'johnpapa/angular-cli' }
             }
            steps {
                 sh 'npm install'
            }
    }

    stage('ng build') {
                  agent {
                     docker { image 'johnpapa/angular-cli' }
                 }
                steps {
                    echo "Hello World!"
                    sh "ng build --prod"
                }
     }

     stage('ls la dist') {
           steps {
                  echo "Hello World!"
                    sh "ls -la"
          }
    }


    stage('Building image') {
      steps{
       script {
              docker.withRegistry('https://registry-1.docker.io/v2/', 'docker_hub') {
              def customImage = docker.build registry + ":$BUILD_NUMBER"
              customImage.push()
          }
        }
      }
    }
  }
}
